import './universal.module';
import '../router/router.module';
import '../storage/storage.module';
import '../channel/socket/socket-channel.module';
import '../event/event.module';
import '../api/entity/modify-entity-payload-factory.module';
import '../component/field/field.module';
import '../permissions/permissions.module';
import './application.effects';
