branches:
    only:
        - master
language: node_js
node_js:
  - "8"
install:
  - npm install opencollective
script:
  - npm run lint
  - npm run scss
  - npm run build
  - npm run test
sudo: required  
addons:
  chrome: stable
