export const DI_TYPES = {
  Api: Symbol('Api'),
  DateConverter: Symbol('DateConverter'),
  NumberConverter: Symbol('NumberConverter'),
  DynamicRoutes: Symbol('DynamicRoutes'),
  EventManager: Symbol('EventManager'),
  ModifyEntityPayloadFactory: Symbol('ModifyEntityPayloadFactory'),
  Menu: Symbol('Menu'),
  FieldsOptions: Symbol('FieldsOptions'),
  Permission: Symbol('Permission'),
  Router: Symbol('Router'),
  Routes: Symbol('Routes'),
  Settings: Symbol('Settings'),
  Storage: Symbol('Storage'),
  NotVersionedStorage: Symbol('NotVersionedStorage'),
  CloudStorage: Symbol('CloudStorage'),
  Store: Symbol('Store'),
  Translate: Symbol('Translate'),
  Transport: Symbol('Transport'),
  TransportFactory: Symbol('TransportFactory'),
  TransportTokenAccessor: Symbol('TransportTokenAccessor'),
  TransportRequestFactory: Symbol('TransportRequestFactory'),
  TransportPayloadAnalyzer: Symbol('TransportPayloadAnalyzer'),
  TransportErrorInterceptor: Symbol('TransportErrorInterceptor'),
  UIPlugins: Symbol('UIPlugins'),
  UIFactory: Symbol('UIFactory'),
};
