export const DI_TYPES = {
  Api: Symbol('Api'),
  DateConverter: Symbol('DateConverter'),
  NumberConverter: Symbol('NumberConverter'),
  DynamicRoutes: Symbol('DynamicRoutes'),
  EventManager: Symbol('EventManager'),
  Menu: Symbol('Menu'),
  Permission: Symbol('Permission'),
  Router: Symbol('Router'),
  Routers: Symbol('Routers'),
  Settings: Symbol('Settings'),
  Storage: Symbol('Storage'),
  Store: Symbol('Store'),
  Translate: Symbol('Translate'),
  Transport: Symbol('Transport'),
  TransportFactory: Symbol('TransportFactory'),
};
