export const DI_TYPES = Object.freeze({
  Api: Symbol('Api'),
  Auth: Symbol('Auth'),
  Channel: Symbol('Channel'),
  CryptoManager: Symbol('CryptoManager'),
  DatabaseStorage: Symbol('DatabaseStorage'),
  DateConverter: Symbol('DateConverter'),
  DomAccessor: Symbol('DomAccessor'),
  DynamicRoutes: Symbol('DynamicRoutes'),
  EventManager: Symbol('EventManager'),
  FieldsOptions: Symbol('FieldsOptions'),
  FileStorage: Symbol('FileStorage'),
  FullScreenManager: Symbol('FullScreenManager'),
  GeoCoder: Symbol('GeoCoder'),
  Environment: Symbol('Environment'),
  I18n: Symbol('I18n'),
  Lock: Symbol('Lock'),
  LogManager: Symbol('LogManager'),
  Menu: Symbol('Menu'),
  ModifyEntityPayloadFactory: Symbol('ModifyEntityPayloadFactory'),
  NotVersionedPersistentStorage: Symbol('NotVersionedPersistentStorage'),
  NotVersionedSessionStorage: Symbol('NotVersionedSessionStorage'),
  NumberConverter: Symbol('NumberConverter'),
  Permission: Symbol('Permission'),
  Router: Symbol('Router'),
  Routes: Symbol('Routes'),
  Settings: Symbol('Settings'),
  Storage: Symbol('Storage'),
  StorageHelper: Symbol('StorageHelper'),
  Store: Symbol('Store'),
  StateSerializer: Symbol('StateSerializer'),
  Translate: Symbol('Translate'),
  /**/
  WebBootstrapper: Symbol('WebBootstrapper'),
  /**/
  VersionProcessor: Symbol('VersionProcessor'),
  /**/
  Transport: Symbol('Transport'),
  TransportErrorInterceptor: Symbol('TransportErrorInterceptor'),
  TransportFactory: Symbol('TransportFactory'),
  TransportRequestDataFactory: Symbol('TransportRequestDataFactory'),
  TransportRequestPayloadFactory: Symbol('TransportRequestPayloadFactory'),
  TransportRequestProvider: Symbol('TransportRequestProvider'),
  TransportResponseAccessor: Symbol('TransportResponseAccessor'),
  TransportResponseFactory: Symbol('TransportResponseFactory'),
  TransportTokenAccessor: Symbol('TransportTokenAccessor'),
  /**/
  UIDefaultFactory: Symbol('UIDefaultFactory'),
  UIFactory: Symbol('UIFactory'),
  UIIconFactory: Symbol('UIIconFactory'),
  UIPlugins: Symbol('UIPlugins'),
});
